project:
  type: website

website:
  title: "AniScope"
  navbar:
    left:
      - docs/assembly.qmd
      - href: docs/usage.qmd
        text: Usage Guide
      - docs/parts.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: docs/styles.css
    toc: true



