[tool.poetry]
name = "aniscope"
version = "0.2.0"
description = ""
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
mkdocs-material = "^9.1.17"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
